-- Stable amenities used by room profiles. This catalog includes only features
-- that can be promised for one room; property-wide facilities stay elsewhere.
INSERT INTO "AmenityRoom" ("id", "name", "category")
VALUES
	('wifi', 'Wi-Fi en la habitación', 'Conectividad'),
	('workspace', 'Espacio de trabajo', 'Conectividad'),
	('desk', 'Escritorio', 'Conectividad'),
	('usb_outlets', 'Enchufes USB junto a la cama', 'Conectividad'),
	('telephone', 'Teléfono', 'Conectividad'),
	('air_conditioning', 'Aire acondicionado', 'Confort'),
	('heating', 'Calefacción', 'Confort'),
	('fan', 'Ventilador', 'Confort'),
	('soundproofing', 'Insonorización', 'Confort'),
	('blackout_curtains', 'Cortinas opacas', 'Confort'),
	('mosquito_net', 'Mosquitero', 'Confort'),
	('private_bathroom', 'Baño privado', 'Baño'),
	('shared_bathroom', 'Baño compartido', 'Baño'),
	('shower', 'Ducha', 'Baño'),
	('bathtub', 'Bañera', 'Baño'),
	('bidet', 'Bidé', 'Baño'),
	('hairdryer', 'Secador de pelo', 'Baño'),
	('towels', 'Toallas', 'Baño'),
	('toiletries', 'Artículos de aseo', 'Baño'),
	('bathrobe', 'Bata de baño', 'Baño'),
	('closet', 'Armario o clóset', 'Dormitorio'),
	('linens', 'Ropa de cama', 'Dormitorio'),
	('extra_pillows_blankets', 'Almohadas y mantas adicionales', 'Dormitorio'),
	('hangers', 'Ganchos para ropa', 'Dormitorio'),
	('iron', 'Plancha para ropa', 'Dormitorio'),
	('ironing_board', 'Tabla de planchar', 'Dormitorio'),
	('extra_long_beds', 'Camas extra largas', 'Dormitorio'),
	('tv', 'Televisión', 'Entretenimiento'),
	('smart_tv', 'Smart TV', 'Entretenimiento'),
	('cable_channels', 'Canales por cable', 'Entretenimiento'),
	('streaming_services', 'Servicios de streaming', 'Entretenimiento'),
	('kitchenette', 'Cocina pequeña', 'Cocina y comedor'),
	('full_kitchen', 'Cocina completa', 'Cocina y comedor'),
	('refrigerator', 'Refrigerador', 'Cocina y comedor'),
	('minibar', 'Minibar', 'Cocina y comedor'),
	('microwave', 'Microondas', 'Cocina y comedor'),
	('coffee_maker', 'Cafetera', 'Cocina y comedor'),
	('electric_kettle', 'Hervidor eléctrico', 'Cocina y comedor'),
	('dining_area', 'Zona de comedor', 'Cocina y comedor'),
	('safe', 'Caja fuerte', 'Seguridad'),
	('smoke_detector', 'Detector de humo', 'Seguridad'),
	('carbon_monoxide_detector', 'Detector de monóxido de carbono', 'Seguridad'),
	('fire_extinguisher', 'Extintor', 'Seguridad'),
	('first_aid_kit', 'Botiquín', 'Seguridad'),
	('step_free_access', 'Acceso sin escalones', 'Accesibilidad'),
	('accessible_bathroom', 'Baño accesible', 'Accesibilidad'),
	('shower_grab_bar', 'Barra de apoyo en la ducha', 'Accesibilidad'),
	('toilet_grab_bar', 'Barra de apoyo junto al inodoro', 'Accesibilidad'),
	('shower_chair', 'Silla para ducha', 'Accesibilidad'),
	('crib', 'Cuna disponible', 'Familias'),
	('high_chair', 'Silla alta para niños', 'Familias')
ON CONFLICT ("id") DO UPDATE
SET "name" = EXCLUDED."name", "category" = EXCLUDED."category";
