import { FinancialExceptionRepository } from "@/modules/financial/infrastructure/repositories/FinancialExceptionRepository"
import { FinancialReferenceRepository } from "@/modules/financial/infrastructure/repositories/FinancialReferenceRepository"
import { FinancialReviewEventRepository } from "@/modules/financial/infrastructure/repositories/FinancialReviewEventRepository"
import { FinancialSettlementRecordRepository } from "@/modules/financial/infrastructure/repositories/FinancialSettlementRecordRepository"
import { CommissionSnapshotRepository } from "@/modules/financial/infrastructure/repositories/CommissionSnapshotRepository"
import { PaymentTransactionRepository } from "@/modules/financial/infrastructure/repositories/PaymentTransactionRepository"
import { PayoutRecordRepository } from "@/modules/financial/infrastructure/repositories/PayoutRecordRepository"
import { ProviderFinancialProfileRepository } from "@/modules/financial/infrastructure/repositories/ProviderFinancialProfileRepository"
import { ProviderPayableSnapshotRepository } from "@/modules/financial/infrastructure/repositories/ProviderPayableSnapshotRepository"
import { ProviderStatementRepository } from "@/modules/financial/infrastructure/repositories/ProviderStatementRepository"
import { ReconciliationMatchRepository } from "@/modules/financial/infrastructure/repositories/ReconciliationMatchRepository"
import { RefundHandoffRepository } from "@/modules/financial/infrastructure/repositories/RefundHandoffRepository"

export const financialExceptionRepository = new FinancialExceptionRepository()
export const financialReferenceRepository = new FinancialReferenceRepository()
export const refundHandoffRepository = new RefundHandoffRepository()
export const financialReviewEventRepository = new FinancialReviewEventRepository()
export const paymentTransactionRepository = new PaymentTransactionRepository()
export const financialSettlementRecordRepository = new FinancialSettlementRecordRepository()
export const reconciliationMatchRepository = new ReconciliationMatchRepository()
export const providerFinancialProfileRepository = new ProviderFinancialProfileRepository()
export const commissionSnapshotRepository = new CommissionSnapshotRepository()
export const providerPayableSnapshotRepository = new ProviderPayableSnapshotRepository()
export const payoutRecordRepository = new PayoutRecordRepository()
export const providerStatementRepository = new ProviderStatementRepository()
