import { postgresDb } from "./client"

/**
 * Transitional server-side database facade.
 *
 * This intentionally exposes a finite API while older consumers migrate toward
 * domain repositories. Do not add wildcard re-exports here: they hide the
 * persistence boundary and force Vite to load the entire Drizzle/schema graph.
 */
export {
	and,
	asc,
	avg,
	count,
	desc,
	eq,
	gt,
	gte,
	inArray,
	isNotNull,
	isNull,
	lt,
	lte,
	ne,
	or,
	sql,
} from "drizzle-orm"

export {
	AmenityRoom,
	Booking,
	BookingLineItem,
	BookingPolicySnapshot,
	BookingTaxFee,
	BookingVoucher,
	CancellationTier,
	CommercialRule,
	CommercialRuleApplication,
	CommercialRuleSet,
	CommissionSnapshot,
	DailyInventory,
	EffectiveAvailability,
	EffectivePricing,
	EffectiveRestriction,
	FinancialExceptionRecord,
	FinancialProviderSummary,
	FinancialReference,
	FinancialReviewEvent,
	FinancialSettlementRecord,
	FiscalActivityEvent,
	FiscalChannelPublication,
	FiscalExportJob,
	FiscalReconciliationCase,
	GeoPlace,
	GeoPlaceAlias,
	GeoPlaceClosure,
	GeoPlaceContent,
	GeoPlaceExternalId,
	Hold,
	Hotel,
	HouseRule,
	Image,
	ImageUpload,
	InventoryLock,
	InventoryResource,
	Limousine,
	MarketplaceCommercialCertificationRun,
	MarketplaceEvent,
	Package,
	PaymentTransaction,
	PayoutRecord,
	Policy,
	PolicyAssignment,
	PolicyAuditLog,
	PolicyExceptionRule,
	PolicyGroup,
	PolicyRule,
	PricingBulkOperationItem,
	PricingBulkOperationJob,
	Product,
	ProductCategory,
	ProductCategoryLink,
	ProductContent,
	ProductGeoPlace,
	ProductGeoPlaceActivity,
	ProductImage,
	ProductLocation,
	ProductOperationalSurface,
	ProductReview,
	ProductService,
	ProductServiceAttribute,
	Provider,
	ProviderAuditLog,
	ProviderComplianceAssignment,
	ProviderConfigurationState,
	ProviderDocument,
	ProviderExternalCalendar,
	ProviderExternalCalendarConflict,
	ProviderExternalCalendarEvent,
	ProviderExternalCalendarExport,
	ProviderFinancialProfile,
	ProviderIntegrationCertification,
	ProviderIntegrationConnection,
	ProviderIntegrationCredential,
	ProviderIntegrationIncident,
	ProviderIntegrationMapping,
	ProviderIntegrationSyncJob,
	ProviderIntegrationSyncRun,
	ProviderInvitation,
	ProviderPayableSnapshot,
	ProviderPaymentAccount,
	ProviderProfile,
	ProviderStatement,
	ProviderTaxConfiguration,
	ProviderUser,
	ProviderVerification,
	RatePlan,
	RatePlanConditionState,
	RatePlanOccupancyPolicy,
	ReconciliationMatch,
	RefundHandoffRecord,
	RefundLedger,
	RefundQuote,
	RoomType,
	SearchMaterializationLog,
	SearchUnitView,
	TaxFeeAssignment,
	TaxFeeDefinition,
	TaxFeeDefinitionDraft,
	TaxFeeDefinitionVersion,
	Tour,
	TourBookingQuestion,
	TourOperationalResource,
	TourPrivateRequest,
	TourResourceAssignment,
	TourSlotProfile,
	TourTicketType,
	User,
	Variant,
	VariantCapacity,
	VariantImage,
	VariantInventoryConfig,
	VariantRoomAmenity,
	VariantRoomBed,
	VariantRoomProfile,
} from "./schema/tables"

export const db = postgresDb

export function first<T>(rows: readonly T[]): T | undefined {
	return rows[0]
}
