export type DatabaseDomain =
	| "provider"
	| "catalog"
	| "policy"
	| "inventory"
	| "pricing"
	| "taxes"
	| "booking"
	| "financial"

export const databaseTablesByDomain = {
	provider: [
		"Provider",
		"ProviderProfile",
		"ProviderDocument",
		"ProviderTaxConfiguration",
		"ProviderPaymentAccount",
		"ProviderIntegrationConnection",
		"ProviderIntegrationCredential",
		"ProviderIntegrationMapping",
		"ProviderIntegrationCertification",
		"ProviderIntegrationSyncRun",
		"ProviderIntegrationSyncJob",
		"ProviderIntegrationIncident",
		"ProviderExternalCalendar",
		"ProviderExternalCalendarEvent",
		"ProviderExternalCalendarConflict",
		"ProviderExternalCalendarExport",
		"ProviderAuditLog",
		"ProviderComplianceAssignment",
		"ProviderConfigurationState",
		"ProviderVerification",
		"ProviderUser",
		"ProviderInvitation",
		"User",
		"ProviderFinancialProfile",
		"ProviderPayableSnapshot",
		"ProviderStatement",
	],
	catalog: [
		"GeoPlace",
		"GeoPlaceClosure",
		"GeoPlaceAlias",
		"GeoPlaceContent",
		"GeoPlaceExternalId",
		"RoomType",
		"AmenityRoom",
		"Image",
		"ImageUpload",
		"ProductImage",
		"VariantImage",
		"Product",
		"ProductGeoPlace",
		"ProductGeoPlaceActivity",
		"MarketplaceCommercialCertificationRun",
		"ProductOperationalSurface",
		"HouseRule",
		"ProductContent",
		"ProductLocation",
		"Hotel",
		"Tour",
		"TourSlotProfile",
		"TourDepartureInstance",
		"TourOperationalResource",
		"TourResourceAssignment",
		"TourTicketType",
		"TourBookingQuestion",
		"TourPrivateRequest",
		"Package",
		"Limousine",
		"Variant",
		"VariantCapacity",
		"VariantRoomProfile",
		"VariantRoomBed",
		"VariantRoomAmenity",
		"ProductService",
		"ProductServiceAttribute",
		"ProductCategory",
		"ProductCategoryLink",
		"ProductReview",
		"MarketplaceEvent",
	],
	policy: [
		"PolicyGroup",
		"Policy",
		"PolicyAssignment",
		"CancellationTier",
		"PolicyRule",
		"PolicyExceptionRule",
		"PolicyAuditLog",
	],
	inventory: [
		"VariantInventoryConfig",
		"InventoryResource",
		"DailyInventory",
		"EffectiveAvailability",
		"ProviderExternalCalendarEvent",
		"InventoryLock",
		"Hold",
	],
	pricing: [
		"SearchUnitView",
		"SearchMaterializationLog",
		"RatePlan",
		"RatePlanConditionState",
		"RatePlanOccupancyPolicy",
		"CommercialRuleSet",
		"CommercialRule",
		"CommercialRuleApplication",
		"EffectiveRestriction",
		"EffectivePricing",
	],
	taxes: [
		"TaxFeeDefinition",
		"TaxFeeDefinitionVersion",
		"TaxFeeAssignment",
		"FiscalActivityEvent",
		"FiscalExportJob",
		"FiscalReconciliationCase",
		"FiscalChannelPublication",
		"BookingTaxFee",
	],
	booking: ["Booking", "BookingVoucher", "BookingLineItem", "BookingPolicySnapshot"],
	financial: [
		"FinancialExceptionRecord",
		"FinancialReference",
		"RefundHandoffRecord",
		"RefundQuote",
		"RefundLedger",
		"FinancialReviewEvent",
		"PaymentTransaction",
		"FinancialSettlementRecord",
		"ReconciliationMatch",
		"ProviderFinancialProfile",
		"FinancialProviderSummary",
		"CommissionSnapshot",
		"ProviderPayableSnapshot",
		"PayoutRecord",
		"ProviderStatement",
	],
} as const satisfies Record<DatabaseDomain, readonly string[]>

export const databaseTableNames = [
	...new Set(Object.values(databaseTablesByDomain).flat()),
] as readonly string[]
