import { readFileSync } from "node:fs"
import { expect, test } from "vitest"
const root = new URL("../../", import.meta.url)
const read = (path: string) => readFileSync(new URL(path, root), "utf8")
test("fiscality uses a contextual header, segmented navigation and progressive filters", () => {
	expect(read("src/layouts/FiscalWorkspaceLayout.astro")).toContain("Configuración comercial")
	expect(read("src/layouts/FiscalWorkspaceLayout.astro")).toContain("Relacionadas")
	const fiscalLayout = read("src/layouts/FiscalWorkspaceLayout.astro")
	expect(fiscalLayout).toMatch(/summary[\s\S]*?fastt-button[\s\S]*?>Relacionadas</)
	expect(fiscalLayout).not.toMatch(/summary[\s\S]*?rounded-md[\s\S]*?>Relacionadas</)
	expect(read("src/components/tax-fees/FiscalWorkspaceTabs.astro")).toContain("TabsInsidePanel")
	expect(read("src/components/tax-fees/FiscalWorkspaceTabs.astro")).toContain("fastt-tabs-inside-panel__item")
	expect(read("src/components/tax-fees/FiscalWorkspaceTabs.astro")).toContain('data-astro-prefetch="viewport"')
	expect(read("src/layouts/FiscalWorkspaceLayout.astro")).toContain("Identidad fiscal:")
	expect(read("src/layouts/FiscalWorkspaceLayout.astro")).toContain("space-y-6 md:space-y-8")
	expect(read("src/layouts/FiscalWorkspaceLayout.astro")).toContain("border-b border-slate-800 pb-5")
	const reviewCenter = read("src/components/tax-fees/FiscalReviewCenter.tsx")
	expect(reviewCenter).toContain("Revisión pendiente")
	expect(reviewCenter).toContain("Configuración")
	expect(reviewCenter).toContain("Sugerencias")
	expect(read("src/components/tax-fees/TaxFeePage.tsx")).toContain("Filtrar definiciones visibles")
	expect(read("src/components/tax-fees/TaxFeePage.tsx")).toContain("Limpiar filtros")
	expect(read("src/components/tax-fees/TaxFeePage.tsx")).toContain('if (mode !== "idle")')
	expect(read("src/components/tax-fees/TaxFeePage.tsx")).toContain("Volver a definiciones")
})
