import { readFileSync } from "node:fs"
import { expect, test } from "vitest"

const root = new URL("../../", import.meta.url)
const read = (path: string) => readFileSync(new URL(path, root), "utf8")

test("the fiscal assignment workspace exposes a resolved hierarchy and bulk operations", () => {
	const matrix = read("src/components/tax-fees/FiscalAssignmentsMatrix.tsx")
	const tree = read("src/pages/api/provider/tax-fees/assignments/tree.ts")
	const bulk = read("src/pages/api/provider/tax-fees/assignments/bulk.ts")
	const migration = read("db/migrations/20260811_tax_fee_assignment_matrix.sql")

	expect(matrix).toContain("Incluir reglas heredadas")
	expect(matrix).toContain("Solo conflictos")
	expect(matrix).toContain("Cobertura")
	expect(matrix).not.toContain("Vista avanzada")
	expect(matrix).toContain("Buscar cobertura")
	expect(matrix).toContain("Afecta")
	expect(matrix).toContain("Ver detalle")
	expect(matrix).toContain("SideSheet")
	expect(matrix).toContain("parentCoverageStatus")
	expect(matrix).toContain("isPathPrefix")
	expect(matrix).toContain("selectedScopeId")
	expect(matrix).toContain("initialDefinitionId")
	expect(matrix).toContain("setSelectedRule(initialDefinitionId)")
	expect(matrix).toContain("Define dónde comienza a aplicar la regla publicada")
	expect(matrix).toContain("scope: target.scope")
	expect(matrix).toContain('params.set("scope", selectedScopeId)')
	expect(matrix).toContain('params.set("definitionId", initialDefinitionId)')
	expect(matrix).toContain("Volver a herencia")
	expect(matrix).toContain("Inicio de cobertura")
	expect(matrix).toContain("Las nuevas tarifas dentro de este nivel heredarán la regla")
	expect(matrix).toContain("Asignar en este nivel")
	expect(matrix).toContain('operation: "preview"')
	expect(matrix).toContain("initialTargetScope")
	expect(matrix).toContain("initialTargetId")
	expect(tree).toContain("resolveEffectiveTaxFeesUseCase")
	expect(tree).toContain("directAssignments")
	expect(tree).toContain("assignableDefinitions")
	expect(tree).toContain("jurisdictionJson")
	expect(tree).toContain("selectedScopeId")
	expect(tree).toContain("requestedDefinitionId")
	expect(tree).toContain("fiscal:assignment-tree")
	expect(bulk).toContain("db.transaction")
	expect(bulk).toContain("ensureOwned")
	expect(bulk).toContain('definition.editingState === "draft"')
	expect(bulk).toContain("definition.jurisdictionJson")
	expect(bulk).toContain('operation === "preview"')
	expect(bulk).toContain("Se acumulará con")
	expect(migration).toContain("TaxFeeAssignment_active_equivalent_unique")
})
