import { readFileSync } from "node:fs"
import { expect, test } from "vitest"

const root = new URL("../../", import.meta.url)
const read = (path: string) => readFileSync(new URL(path, root), "utf8")

test("the fiscal simulator certifies a PriceQuote without mutating fiscal data", () => {
	const simulator = read("src/components/tax-fees/FiscalSimulator.tsx")
	const preview = read("src/pages/api/provider/tax-fees/preview.ts")
	const resources = read("src/lib/taxes-fees/fiscal-workspace-resources.ts")
	const route = read("src/pages/provider/settings/tax-fees/simulator.astro")
	const definitionsPage = read("src/components/tax-fees/TaxFeePage.tsx")
	const readiness = read("src/pages/api/provider/tax-fees/simulation-readiness.ts")
	const readinessModel = read("src/lib/taxes-fees/fiscal-simulation-readiness.ts")
	const quote = read("src/modules/pricing/domain/price-quote.ts")
	const picker = read("src/components/ui-react/TravelersPicker.tsx")

	expect(simulator).toContain("Comparar este borrador con la versión publicada")
	expect(simulator).toContain("Vista técnica")
	expect(simulator).toContain("Exportar")
	expect(simulator).toContain("Continuar a publicación")
	expect(simulator).toContain("Comprobar ${selectedDefinition.name}")
	expect(simulator).toContain("ruleLockedFromDefinitions")
	expect(simulator).toContain("Regla a comprobar")
	expect(simulator).toContain("Contexto comercial")
	expect(simulator).toContain("Reserva de prueba")
	expect(simulator).toContain("Condiciones fiscales")
	expect(simulator).toContain("Opciones avanzadas")
	expect(simulator).toContain("Simular cotización")
	expect(simulator).not.toContain("publishAfterSimulation=1")
	expect(simulator).toContain("Jurisdicción de la regla")
	expect(simulator).toContain("Se toma de la definición seleccionada")
	expect(simulator).toContain("ReadOnlyField")
	expect(simulator).toContain("country: simulationCountry")
	expect(simulator).toContain("Escenario recomendado")
	expect(simulator).toContain("Cambiar datos")
	expect(simulator).toContain('pricingMode: useManualPrice ? "manual" : "effective"')
	expect(preview).toContain("buildPriceQuote")
	expect(preview).toContain("resolveFiscalSimulationPricing")
	expect(preview).toContain('error: "simulation_context_unavailable"')
	expect(preview).toContain('source: "simulation"')
	expect(preview).toContain('status: "active"')
	expect(resources).toContain("getRecommendedFiscalSimulationContext")
	expect(resources).toContain("FiscalSimulationIssue")
	expect(resources).toContain("fiscalRatePlanDisplayLabel")
	expect(resources).toContain("selectFiscalSimulationDiagnosticPlan")
	expect(resources).toContain("resolveFiscalSimulationPricing")
	expect(route).toContain("recommendedContext")
	expect(route).toContain("simulationIssues")
	expect(route).toContain("simulationNotice")
	expect(route).toContain("getFiscalSimulationReadiness")
	expect(route).toContain('Astro.url.searchParams.get("definitionId")')
	expect(route).not.toContain('searchParams.get("edit")')
	expect(simulator).toContain("DatesModal")
	expect(simulator).toContain("TravelersPicker")
	expect(picker).toContain("Adultos")
	expect(picker).toContain("Niños")
	expect(picker).toContain("Habitaciones o cantidad")
	expect(simulator).toContain("fastt-section-icon")
	expect(simulator).toContain("blockingIssues.map")
	expect(simulator).toContain("/api/provider/tax-fees/simulation-readiness")
	expect(simulator).toContain("notice.intro")
	expect(readinessModel).toContain("Falta preparar una cotización real")
	expect(readinessModel).toContain("esa opción no certifica búsqueda ni checkout")
	expect(readinessModel).toContain("Para certificar ${input.definitionName}")
	expect(readinessModel).toContain("coverage_other_product")
	expect(definitionsPage).not.toContain("simulation-readiness")
	expect(definitionsPage).not.toContain("Falta esto para probarlo con una reserva real")
	expect(definitionsPage).toContain("Lista para publicar")
	expect(definitionsPage).toContain("Comprobar cobro")
	expect(definitionsPage).not.toContain("&mode=manual")
	expect(route).toContain('Astro.url.searchParams.get("mode") === "manual"')
	expect(readiness).toContain("getFiscalSimulationReadiness")
	expect(readiness).toContain("getProviderIdFromRequest")
	expect(quote).toContain('"simulation"')
})
