import { readFileSync } from "node:fs"
import { expect, test } from "vitest"

const root = new URL("../../", import.meta.url)
const read = (path: string) => readFileSync(new URL(path, root), "utf8")

test("the fiscal simulator certifies a PriceQuote without mutating fiscal data", () => {
	const simulator = read("src/components/tax-fees/FiscalSimulator.tsx")
	const preview = read("src/pages/api/provider/tax-fees/preview.ts")
	const resources = read("src/lib/taxes-fees/fiscal-workspace-resources.ts")
	const route = read("src/pages/provider/settings/tax-fees/simulator.astro")
	const quote = read("src/modules/pricing/domain/price-quote.ts")

	expect(simulator).toContain("Comparar este borrador con la versión publicada")
	expect(simulator).toContain("Vista técnica")
	expect(simulator).toContain("Exportar")
	expect(simulator).toContain("Continuar a publicación")
	expect(simulator).toContain("Comprobar ${selectedDefinition.name}")
	expect(simulator).toContain("Contexto comercial")
	expect(simulator).toContain("Reserva de prueba")
	expect(simulator).toContain("Condiciones fiscales")
	expect(simulator).toContain("Opciones avanzadas")
	expect(simulator).toContain("Simular cotización")
	expect(simulator).not.toContain("publishAfterSimulation=1")
	expect(simulator).toContain("Jurisdicción de la regla")
	expect(simulator).toContain("Se toma de la definición seleccionada")
	expect(simulator).toContain("ReadOnlyField")
	expect(simulator).toContain("country: simulationCountry")
	expect(simulator).toContain("Escenario recomendado")
	expect(simulator).toContain("Cambiar datos")
	expect(simulator).toContain('pricingMode: useManualPrice ? "manual" : "effective"')
	expect(preview).toContain("buildPriceQuote")
	expect(preview).toContain("resolveFiscalSimulationPricing")
	expect(preview).toContain('error: "simulation_context_unavailable"')
	expect(preview).toContain('source: "simulation"')
	expect(preview).toContain('status: "active"')
	expect(resources).toContain("getRecommendedFiscalSimulationContext")
	expect(resources).toContain("FiscalSimulationIssue")
	expect(resources).toContain("missing_availability")
	expect(resources).toContain("missing_price")
	expect(resources).toContain("resolveFiscalSimulationPricing")
	expect(route).toContain("recommendedContext")
	expect(route).toContain("simulationIssues")
	expect(simulator).toContain("Falta preparar una cotización real")
	expect(simulator).toContain("simulationIssues.map")
	expect(simulator).toContain("esa opción no certifica búsqueda ni checkout")
	expect(quote).toContain('"simulation"')
})
