import { existsSync, readFileSync } from "node:fs"
import { resolve } from "node:path"
import { describe, expect, it } from "vitest"

function read(path: string) {
	return readFileSync(resolve(process.cwd(), path), "utf8")
}

describe("ui/pricing contextual extension", () => {
	it("rate plans no longer expose a separate pricing bulk surface", () => {
		const manage = read("src/pages/rates/plans/manage.astro")
		const routes = read("src/lib/routes.ts")

		expect(existsSync(resolve(process.cwd(), "src/pages/rates/plans/index.astro"))).toBe(false)
		expect(manage).not.toContain("pricingBulk")
		expect(routes).not.toContain("pricingBulk")
		expect(routes).not.toContain("/pricing/bulk")
	})

	it("rates calendar keeps extension contextual inside the calendar shell", () => {
		const source = read("src/pages/rates/calendar.astro")

		expect(source).toContain("Cambio manual de precio")
		expect(source).toContain("Reglas simples que actúan después")
		expect(source).toContain("data-pricing-automation-presets")
		expect(source).toContain("Descuentos")
		expect(source).toContain("Aumentos")
		expect(source).toContain("Precio fijo")
		expect(source).toContain("Crear ayuda recurrente")
		expect(source).toContain("Eliminar ayuda recurrente")
		expect(source).toContain("delete-pricing-automation")
		expect(source).not.toContain("Simple primero")
		expect(source).not.toContain("Ayudas automáticas recurrentes")
		expect(source).toContain("Detalle avanzado")
		expect(source).toContain("pricingAddMonthBtn")
		expect(source).toContain("Añadir mes siguiente")
		expect(source).not.toContain("Acciones avanzadas para la selección")
		expect(source).toContain("Hacer recurrente")
		expect(source).toContain("data-pricing-extension-drawer")
		expect(source).toContain("data-pricing-open-extension")
		expect(source).toContain("pricingExtensionDrawer")
		expect(source).toContain("Extender este cambio")
		expect(source).toContain("Copiar precio")
		expect(source).toContain("Precio a copiar")
		expect(source).toContain("Ajuste solo si existe")
		expect(source).toContain("pricing-date-selected")
		expect(source).toContain("Revisar extensión")
		expect(source).toContain("buildExtensionPayload")
		expect(source).toContain("summarizeExtensionPreview")
		expect(source).toContain("data-pricing-apply-result-card")
		expect(source).toContain("renderOperationResult")
		expect(source).toContain("buildRecoveryGuidance")
		expect(source).toContain("Detalle técnico")
		expect(source).toContain("pricingOperationCopy")
		expect(source).toContain("pricingRangeOperationType")
		expect(source).toContain("pricingExtensionOperationType")
		expect(source).not.toContain("Aumentar este precio por %")
		expect(source).not.toContain("Reducir este precio por %")
		expect(source).not.toContain("Ajustar este precio por monto")
		expect(source).not.toContain("Manual = cambia ahora")
		expect(source).toContain("nightsLabel(days)")
		expect(source).toContain("data-pricing-day-card")
		expect(source).toContain("syncRangeValueFromSingleDate")
		expect(source).not.toContain("pricingDayEditor")
		expect(source).not.toContain("Guardar fecha")
		expect(source).toContain("mobile-calendar-action-sheet")
		expect(source).toContain("mobile-calendar-grid")
		expect(source).not.toContain("data-pricing-range-date")
		expect(source).not.toContain("data-pricing-day-form")
		expect(source).toContain("/api/pricing/rules/v2/bulk-preview")
		expect(source).toContain("/api/pricing/rules/v2/bulk-apply")
		expect(source).toContain("setApplyNeedsConfirmation")
		expect(source).toContain("priority: 1000")
		expect(source).toContain('contextKey: "manual"')
		expect(read("src/lib/pricing/pricingExtensionPresenter.ts")).toContain(
			"pricingExtensionOperationOptions"
		)
		expect(source).not.toContain("/pricing/bulk")
		expect(source).not.toContain("data-pricing-bulk-context-link")
		expect(source).not.toContain("buildBulkContextHref")
		expect(source).not.toContain("syncBulkContextLinks")
		expect(source).not.toContain("Automatización de precios</p>")
		expect(source).not.toContain("Flujo avanzado multi-plan")
	})
})
