import { existsSync, readFileSync } from "node:fs"
import { resolve } from "node:path"
import { describe, expect, it } from "vitest"

function read(path: string) {
	return readFileSync(resolve(process.cwd(), path), "utf8")
}

describe("ui/pricing contextual extension", () => {
	it("rate plans no longer expose a separate pricing bulk surface", () => {
		const manage = read("src/pages/rates/plans/manage.astro")
		const routes = read("src/lib/routes.ts")

		expect(existsSync(resolve(process.cwd(), "src/pages/rates/plans/index.astro"))).toBe(false)
		expect(manage).not.toContain("pricingBulk")
		expect(routes).not.toContain("pricingBulk")
		expect(routes).not.toContain("/pricing/bulk")
	})

	it("rates calendar keeps manual extension contextual and sends recurring rules to Reglas de venta", () => {
		const calendar = read("src/pages/rates/calendar.astro")
		const restrictions = read("src/pages/rates/restrictions.astro")
		const operationalPanel = read("src/components/rates/CalendarOperationalPanel.astro")
		const automationPanel = read("src/components/rates/PricingAutomationPanel.astro")
		const controller = read("src/lib/rates/calendarOperationalController.ts")
		const source = `${calendar}\n${restrictions}\n${operationalPanel}\n${automationPanel}\n${controller}`

		expect(calendar).toContain("CalendarOperationalPanel")
		expect(calendar).not.toContain("PricingAutomationPanel")
		expect(restrictions).toContain("PricingAutomationPanel")
		expect(operationalPanel).toContain("Cambio manual de precio")
		expect(calendar).not.toContain("data-pricing-automation-drawer")
		expect(calendar).not.toContain("pricingAutomationCloseBtn")
		expect(automationPanel).toContain("data-pricing-automation-presets")
		expect(restrictions).toContain("Descuentos")
		expect(restrictions).toContain("Aumentos")
		expect(restrictions).toContain("Precio fijo")
		expect(automationPanel).toContain("Crear regla de precio")
		expect(automationPanel).toContain("Eliminar regla")
		expect(restrictions).toContain("delete-pricing-automation")
		expect(source).not.toContain("Simple primero")
		expect(source).not.toContain("Ayudas automáticas recurrentes")
		expect(source).not.toContain("Detalle avanzado")
		expect(calendar).toContain("pricingAddMonthBtn")
		expect(calendar).toContain("Añadir mes siguiente")
		expect(source).not.toContain("Acciones avanzadas para la selección")
		expect(operationalPanel).toContain("Reglas de venta")
		expect(operationalPanel).toContain("Crear regla de venta")
		expect(operationalPanel.match(/data-panel-restrictions-action/g) ?? []).toHaveLength(1)
		expect(calendar).toContain("data-pricing-extension-drawer")
		expect(operationalPanel).toContain("data-pricing-open-extension")
		expect(controller).toContain("pricingExtensionDrawer")
		expect(operationalPanel).toContain("Extender cambio")
		expect(controller).toContain("Copiar precio")
		expect(calendar).toContain("Precio a copiar")
		expect(operationalPanel).toContain("Mostrar ajustes")
		expect(controller).toContain("pricing-date-selected")
		expect(calendar).toContain("Revisar extensión")
		expect(controller).toContain("buildExtensionPayload")
		expect(controller).toContain("summarizeExtensionPreview")
		expect(calendar).toContain("data-pricing-apply-result-card")
		expect(controller).toContain("renderOperationResult")
		expect(controller).toContain("buildRecoveryGuidance")
		expect(source).not.toContain("Detalle técnico")
		expect(calendar).toContain("pricingOperationCopy")
		expect(operationalPanel).toContain("pricingRangeOperationType")
		expect(calendar).toContain("pricingExtensionOperationType")
		expect(source).not.toContain("Aumentar este precio por %")
		expect(source).not.toContain("Reducir este precio por %")
		expect(source).not.toContain("Ajustar este precio por monto")
		expect(source).not.toContain("Manual = cambia ahora")
		expect(controller).toContain("nightsLabel(days)")
		expect(calendar).toContain("data-pricing-day-card")
		expect(controller).toContain("syncRangeValueFromSingleDate")
		expect(source).not.toContain("pricingDayEditor")
		expect(source).not.toContain("Guardar fecha")
		expect(operationalPanel).toContain("data-panel-manual-price-action")
		expect(operationalPanel).toContain("pricingManualPriceDrawer")
		expect(operationalPanel).not.toContain("mobile-calendar-action-sheet")
		expect(calendar).toContain("mobile-calendar-grid")
		expect(source).not.toContain("data-pricing-range-date")
		expect(source).not.toContain("data-pricing-day-form")
		expect(controller).toContain("/api/pricing/rules/v2/bulk-preview")
		expect(controller).toContain("/api/pricing/rules/v2/bulk-apply")
		expect(controller).toContain("setApplyNeedsConfirmation")
		expect(controller).toContain("priority: 1000")
		expect(controller).toContain('contextKey: "manual"')
		expect(read("src/lib/pricing/pricingExtensionPresenter.ts")).toContain(
			"pricingExtensionOperationOptions"
		)
		expect(source).not.toContain("/pricing/bulk")
		expect(source).not.toContain("data-pricing-bulk-context-link")
		expect(source).not.toContain("buildBulkContextHref")
		expect(source).not.toContain("syncBulkContextLinks")
		expect(source).not.toContain("Automatización de precios</p>")
		expect(source).not.toContain("Flujo avanzado multi-plan")
	})
})
