import { describe, expect, it } from "vitest"
import { readFileSync } from "node:fs"
import { resolve } from "node:path"

function read(path: string) {
	return readFileSync(resolve(process.cwd(), path), "utf8")
}

describe("ui/rateplan bulk pricing wizard", () => {
	it("rates/plans incluye selección múltiple y acción de edición masiva", () => {
		const source = read("src/pages/rates/plans/index.astro")
		expect(source).toContain("data-rateplan-checkbox")
		expect(source).toContain('id="bulkSelectAll"')
		expect(source).toContain('id="bulkEditOpenBtn"')
		expect(source).toContain("Operacion avanzada multi-plan")
		expect(source).toContain("window.location.href = `/pricing/bulk?")
		expect(source).not.toContain("window.location.href = `/rates/plans?")
	})

	it("wizard integra preview y apply con endpoints bulk v2", () => {
		const source = read("src/pages/pricing/bulk.astro")
		expect(source).toContain("Operacion avanzada de pricing")
		expect(source).toContain("el calendario de Pricing es la operacion diaria principal")
		expect(source).toContain("data-bulk-advanced-context")
		expect(source).toContain("pricingOperationCopy.extension.contextTitle")
		expect(source).toContain("pricingOperationCopy.extension.advancedModeTitle")
		expect(source).toContain("pricingOperationCopy.extension.changeTitle")
		expect(source).toContain("pricingOperationCopy.extension.intentSummary")
		expect(source).toContain("soporte y diagnóstico")
		expect(source).toContain('id="bulkContextFrom"')
		expect(source).toContain('id="bulkContextTo"')
		expect(source).toContain("bulkContext")
		expect(source).toContain("syncContextRangeFields")
		expect(source).toContain("Volver a Pricing")
		expect(source).toContain('id="bulkOperationType"')
		expect(source).toContain('id="bulkPreviewBtn"')
		expect(source).toContain('id="bulkApplyBtn"')
		expect(source).toContain('id="bulkExecutiveSummary"')
		expect(source).toContain('id="bulkPreviewCards"')
		expect(source).toContain('id="bulkResultCards"')
		expect(source).toContain('id="bulkPreviewSort"')
		expect(source).toContain("pricingOperationCopy")
		expect(source).toContain("pricingOperationCopy.extension.reviewTitle")
		expect(source).toContain("pricingOperationCopy.bulkApplyAction")
		expect(source).toContain("pricingOperationCopy.extension.technicalTableTitle")
		expect(source).toContain('fetch("/api/pricing/rules/v2/bulk-preview"')
		expect(source).toContain('fetch("/api/pricing/rules/v2/bulk-apply"')
	})

	it("muestra diffs y errores parciales en preview/apply", () => {
		const source = read("src/pages/pricing/bulk.astro")
		expect(source).toContain("changedDays")
		expect(source).toContain("totalDelta")
		expect(source).toContain("calculateRiskSignals")
		expect(source).toContain('id="bulkGlobalAlerts"')
		expect(source).toContain('id="bulkApplyConfirmation"')
		expect(source).toContain('id="bulkPreviewFailures"')
		expect(source).toContain('id="bulkResultFailures"')
		expect(source).toContain("renderPreviewCards")
		expect(source).toContain("renderResultCards")
		expect(source).toContain("renderFailureCard")
		expect(source).toContain("buildRecoveryGuidance")
		expect(source).toContain("Qué hacer ahora")
		expect(source).toContain("Detalle técnico")
		expect(source).toContain("data-bulk-preview-result-cards")
		expect(source).toContain("data-bulk-apply-result-cards")
	})

	it("pricing calendar exposes compact range operations without replacing daily edit", () => {
		const source = read("src/pages/pricing/index.astro")
		expect(source).toContain("Cambio manual de precio")
		expect(source).toContain("Ayudas automáticas recurrentes")
		expect(source).toContain("Tres intenciones, un solo origen")
		expect(source).toContain("Selecciona fechas en el calendario")
		expect(source).toContain("data-pricing-automation-presets")
		expect(source).toContain("Crear ayuda recurrente")
		expect(source).toContain("Simple primero")
		expect(source).toContain("Detalle avanzado")
		expect(source).toContain("Acciones avanzadas para la selección")
		expect(source).toContain("Hacer recurrente")
		expect(source).toContain("data-pricing-extension-drawer")
		expect(source).toContain("data-pricing-open-extension")
		expect(source).toContain("pricingExtensionDrawer")
		expect(source).toContain("Extender este cambio")
		expect(source).toContain("Revisar extensión")
		expect(source).toContain("Abrir detalle avanzado")
		expect(source).toContain("buildExtensionPayload")
		expect(source).toContain("summarizeExtensionPreview")
		expect(source).toContain("data-pricing-apply-result-card")
		expect(source).toContain("renderOperationResult")
		expect(source).toContain("buildRecoveryGuidance")
		expect(source).toContain("Detalle técnico")
		expect(source).toContain("pricingOperationCopy")
		expect(source).toContain("data-pricing-bulk-context-link")
		expect(source).toContain("buildBulkContextHref")
		expect(source).toContain("syncBulkContextLinks")
		expect(source).toContain("nightsLabel(days)")
		expect(source).toContain("data-pricing-day-card")
		expect(source).toContain("syncRangeValueFromSingleDate")
		expect(source).not.toContain("pricingDayEditor")
		expect(source).not.toContain("Guardar fecha")
		expect(source).toContain("mobile-calendar-action-sheet")
		expect(source).toContain("mobile-calendar-grid")
		expect(source).not.toContain("data-pricing-range-date")
		expect(source).not.toContain("data-pricing-day-form")
		expect(source).toContain("/api/pricing/rules/v2/bulk-preview")
		expect(source).toContain("/api/pricing/rules/v2/bulk-apply")
		expect(source).toContain("setApplyNeedsConfirmation")
		expect(source).toContain("priority: 1000")
		expect(source).toContain('contextKey: "manual"')
		expect(source).not.toContain("Automatización de precios</p>")
		expect(source).not.toContain("Flujo avanzado multi-plan")
	})
})
