/** Idiomas ofrecidos en una salida (código ISO 639-1, etiqueta en español). */
export const TOUR_SLOT_LANGUAGE_OPTIONS = [
	{ code: "es", label: "Español" },
	{ code: "en", label: "Inglés" },
	{ code: "pt", label: "Portugués" },
	{ code: "fr", label: "Francés" },
	{ code: "de", label: "Alemán" },
	{ code: "it", label: "Italiano" },
	{ code: "nl", label: "Neerlandés" },
	{ code: "ca", label: "Catalán" },
	{ code: "gl", label: "Gallego" },
	{ code: "eu", label: "Euskera" },
	{ code: "zh", label: "Chino" },
	{ code: "ja", label: "Japonés" },
	{ code: "ko", label: "Coreano" },
	{ code: "ar", label: "Árabe" },
	{ code: "ru", label: "Ruso" },
	{ code: "pl", label: "Polaco" },
	{ code: "sv", label: "Sueco" },
	{ code: "da", label: "Danés" },
	{ code: "nb", label: "Noruego" },
	{ code: "fi", label: "Finlandés" },
	{ code: "el", label: "Griego" },
	{ code: "tr", label: "Turco" },
	{ code: "he", label: "Hebreo" },
	{ code: "hi", label: "Hindi" },
	{ code: "qu", label: "Quechua" },
	{ code: "gn", label: "Guaraní" },
] as const
